from __future__ import annotations

import locale
from collections.abc import Mapping


SUPPORTED_LANGUAGES = ("en", "zh-CN")


STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "language_name": "English",
        "app_title": "SpritePostprocess",
        "language": "Language",
        "new_config_group": "Create a new config",
        "source_path": "Source to scan (only used to create a config)",
        "config_path": "Config file",
        "preset": "Preset",
        "preset_pixel": "Pixel character (strict cleanup + shared fit)",
        "preset_neutral": "Neutral (preserve layout + no cleanup)",
        "preset_help": "A preset only supplies starting values. The JSON remains fully editable.",
        "browse": "Browse…",
        "choose_folder": "Folder…",
        "choose_file": "File…",
        "create_config": "Create Config",
        "open_config": "Open Config",
        "common_tab": "Common Settings",
        "advanced_tab": "Advanced JSON",
        "output_path": "New output directory",
        "output_help": "Processing creates this directory. Keep the config beside it, not inside it.",
        "aseprite_path": "Aseprite executable (or auto)",
        "work_size": "Working canvas (W×H)",
        "output_sizes": "Output sizes",
        "sizes_help": "Comma-separated W×H values; rectangular sizes are supported.",
        "cleanup": "Edge cleanup",
        "cleanup_off": "Off",
        "cleanup_conservative": "Conservative",
        "cleanup_strict": "Strict",
        "layout": "Layout",
        "layout_preserve": "Preserve current placement",
        "layout_shared_fit": "Shared fit for each animation group",
        "occupancy": "Occupancy (%)",
        "preview_frames": "Preview frames",
        "export_group": "Exports",
        "export_aseprite": "Aseprite",
        "export_png_frames": "PNG frames",
        "export_previews": "Animated previews",
        "export_zip": "ZIP package",
        "apply_common": "Apply Common Settings to JSON",
        "apply_help": "Applies only the fields above. Animations, mirrors, matching and other advanced JSON are preserved.",
        "json_title": "Complete JSON config (canonical configuration)",
        "json_help": "Advanced edits are kept when common settings are applied. Save before processing.",
        "save_config": "Save Config",
        "save_run": "Save + Run",
        "verify": "Verify Output",
        "doctor": "Environment Check",
        "open_output": "Open Output Folder",
        "help": "Help",
        "clear_log": "Clear Log",
        "log_title": "Run Log",
        "status": "Status:",
        "ready": "Ready",
        "running": "Running…",
        "complete": "Complete",
        "failed": "Failed (exit code {code})",
        "launch_failed": "Could not start",
        "config_opened": "Opened config: {name}",
        "config_saved": "Saved config: {name}",
        "settings_applied": "Common settings applied to JSON (not saved yet)",
        "select_source": "Select a source file or cancel to choose a folder",
        "select_source_file": "Select an animation source file",
        "select_source_folder": "Select a folder containing animation sources",
        "select_output": "Select a new output directory",
        "select_config_save": "Choose a config file location",
        "select_config_open": "Open a SpritePostprocess config",
        "select_aseprite": "Select the Aseprite executable",
        "json_files": "JSON config",
        "all_files": "All files",
        "executables": "Executables",
        "animation_files": "Animation files",
        "missing_paths_title": "Missing paths",
        "missing_paths": "Choose a source and a new output directory first.",
        "missing_config_title": "Missing config",
        "missing_config_location": "Choose a config file location first.",
        "missing_config_open": "Create or open a config first.",
        "config_not_found": "The config file does not exist. Create or save it first.",
        "core_missing_title": "Core tool missing",
        "core_missing": "Cannot find:\n{path}",
        "task_running_title": "Task already running",
        "task_running": "Wait for the current task to finish.",
        "overwrite_title": "Replace config?",
        "overwrite_config": "The config already exists:\n{path}\n\nReplace it?",
        "replace_failed": "Could not replace config",
        "open_failed": "Could not open config",
        "save_failed": "Could not save config",
        "invalid_json_title": "Invalid JSON",
        "invalid_json": "Line {line}, column {column}: {message}",
        "invalid_settings_title": "Invalid common settings",
        "root_object": "The config root must be a JSON object.",
        "output_required": "The config must contain a non-empty \"output\" path.",
        "output_inside_title": "Invalid config location",
        "output_inside": "The config cannot be stored inside the output directory. Choose a sibling location for the config.",
        "apply_dirty_title": "Apply form changes?",
        "apply_dirty": "Common settings contain unapplied changes. Apply them to the JSON before continuing?\n\nChoose No to cancel.",
        "unsaved_json_title": "Unsaved JSON",
        "unsaved_json": "The JSON editor contains unsaved changes. Save them before processing?\n\nChoose No to cancel.",
        "result_missing_title": "Missing output directory",
        "result_missing": "Choose or load an output directory first.",
        "directory_missing_title": "Directory not found",
        "directory_missing": "The output directory does not exist yet:\n{path}",
        "open_directory_failed": "Could not open directory",
        "help_missing_title": "Help file missing",
        "help_missing": "No local README was found beside the tool.",
        "help_failed": "Could not open help",
        "close_running_title": "Task still running",
        "close_running": "Closing will terminate the current task. Continue?",
        "dependency_hint": "Use Environment Check to identify missing components, then install requirements.txt into the Python runtime selected by Start.cmd as described in the README. Aseprite is only required for Aseprite input/output.",
        "doctor_intro": "Checking Python, image libraries, Tk and Aseprite…",
        "language_saved_warning": "The language works now, but its preference could not be saved: {message}",
        "config_validation_title": "Config validation failed",
        "config_validation": "The config was not loaded or saved because it does not match the supported schema. Your current editor contents were kept.",
        "technical_detail": "Technical detail: ",
        "form_error_general": "One or more common settings are invalid.",
        "form_error_size_format": "Enter sizes as width × height, for example 512×512.",
        "form_error_size_range": "Each width and height must be between 1 and 8192 pixels.",
        "form_error_sizes_empty": "Add at least one output size.",
        "form_error_sizes_duplicate": "Remove duplicate output sizes.",
        "form_error_root_object": "The JSON config must be an object.",
        "form_error_output_empty": "Choose a new output directory.",
        "form_error_cleanup": "Choose one of the available edge-cleanup options.",
        "form_error_layout": "Choose one of the available layout options.",
        "form_error_occupancy_format": "Enter the occupancy as a number from 1 to 100.",
        "form_error_occupancy_range": "Occupancy must be between 1% and 100%.",
        "form_error_preview_format": "Preview frames must be a whole number.",
        "form_error_preview_range": "Preview frames must be between 1 and 10000.",
    },
    "zh-CN": {
        "language_name": "简体中文",
        "app_title": "SpritePostprocess 动画后处理",
        "language": "语言",
        "new_config_group": "创建新配置",
        "source_path": "待扫描素材（仅用于创建配置）",
        "config_path": "配置文件",
        "preset": "预设",
        "preset_pixel": "像素角色（严格清理 + 分组统一适配）",
        "preset_neutral": "中性（保留布局 + 不清理）",
        "preset_help": "预设只提供初始值；之后仍可完整编辑 JSON。",
        "browse": "浏览…",
        "choose_folder": "文件夹…",
        "choose_file": "文件…",
        "create_config": "创建配置",
        "open_config": "打开配置",
        "common_tab": "常用设置",
        "advanced_tab": "高级 JSON",
        "output_path": "新结果目录",
        "output_help": "处理时会新建此目录。配置应放在它旁边，不能放在它里面。",
        "aseprite_path": "Aseprite 可执行文件（或 auto）",
        "work_size": "工作画布（宽×高）",
        "output_sizes": "输出尺寸",
        "sizes_help": "多个宽×高用逗号分隔；支持非正方形尺寸。",
        "cleanup": "边缘白色污染清理",
        "cleanup_off": "关闭",
        "cleanup_conservative": "保守",
        "cleanup_strict": "严格",
        "layout": "布局方式",
        "layout_preserve": "保留当前位置与大小",
        "layout_shared_fit": "同一动画组使用统一适配",
        "occupancy": "画布占比（%）",
        "preview_frames": "预览帧数",
        "export_group": "导出内容",
        "export_aseprite": "Aseprite",
        "export_png_frames": "逐帧 PNG",
        "export_previews": "动画预览",
        "export_zip": "ZIP 压缩包",
        "apply_common": "把常用设置应用到 JSON",
        "apply_help": "只更新上面的字段；动画、镜像、帧匹配和其他高级 JSON 都会保留。",
        "json_title": "完整 JSON 配置（唯一正式配置）",
        "json_help": "应用常用设置时会保留高级修改；处理前需要保存。",
        "save_config": "保存配置",
        "save_run": "保存并运行",
        "verify": "验证结果",
        "doctor": "环境检查",
        "open_output": "打开结果目录",
        "help": "帮助",
        "clear_log": "清空日志",
        "log_title": "运行日志",
        "status": "状态：",
        "ready": "就绪",
        "running": "运行中…",
        "complete": "完成",
        "failed": "失败（退出码 {code}）",
        "launch_failed": "启动失败",
        "config_opened": "已打开配置：{name}",
        "config_saved": "配置已保存：{name}",
        "settings_applied": "常用设置已应用到 JSON（尚未保存）",
        "select_source": "选择素材文件，或取消后选择素材目录",
        "select_source_file": "选择动画素材文件",
        "select_source_folder": "选择包含动画素材的目录",
        "select_output": "选择新的结果目录",
        "select_config_save": "选择配置文件位置",
        "select_config_open": "打开 SpritePostprocess 配置",
        "select_aseprite": "选择 Aseprite 可执行文件",
        "json_files": "JSON 配置",
        "all_files": "所有文件",
        "executables": "可执行文件",
        "animation_files": "动画文件",
        "missing_paths_title": "缺少路径",
        "missing_paths": "请先选择素材和新的结果目录。",
        "missing_config_title": "缺少配置",
        "missing_config_location": "请先选择配置文件位置。",
        "missing_config_open": "请先创建或打开配置。",
        "config_not_found": "配置文件不存在，请先创建或保存。",
        "core_missing_title": "缺少核心工具",
        "core_missing": "找不到：\n{path}",
        "task_running_title": "任务正在运行",
        "task_running": "请等待当前任务结束。",
        "overwrite_title": "替换配置？",
        "overwrite_config": "配置文件已经存在：\n{path}\n\n是否替换？",
        "replace_failed": "替换配置失败",
        "open_failed": "无法打开配置",
        "save_failed": "保存失败",
        "invalid_json_title": "JSON 格式错误",
        "invalid_json": "第 {line} 行，第 {column} 列：{message}",
        "invalid_settings_title": "常用设置无效",
        "root_object": "配置根节点必须是 JSON 对象。",
        "output_required": "配置必须包含非空的 \"output\" 路径。",
        "output_inside_title": "配置位置无效",
        "output_inside": "配置不能放在结果目录内。请把配置放在结果目录旁边。",
        "apply_dirty_title": "应用表单修改？",
        "apply_dirty": "常用设置还有未应用的修改。继续前是否把它们应用到 JSON？\n\n选择“否”会取消本次操作。",
        "unsaved_json_title": "JSON 尚未保存",
        "unsaved_json": "JSON 编辑区包含未保存的修改。处理前是否保存？\n\n选择“否”会取消本次操作。",
        "result_missing_title": "缺少结果目录",
        "result_missing": "请先选择或加载结果目录。",
        "directory_missing_title": "目录不存在",
        "directory_missing": "结果目录尚不存在：\n{path}",
        "open_directory_failed": "无法打开目录",
        "help_missing_title": "缺少帮助文件",
        "help_missing": "工具旁边没有找到本地 README。",
        "help_failed": "无法打开帮助",
        "close_running_title": "任务仍在运行",
        "close_running": "关闭窗口会终止当前任务，是否继续？",
        "dependency_hint": "请先使用“环境检查”确认缺少的组件，再按照 README 的说明，把 requirements.txt 安装到 Start.cmd 选中的 Python 运行环境。只有读写 Aseprite 文件时才需要 Aseprite。",
        "doctor_intro": "正在检查 Python、图像库、Tk 和 Aseprite…",
        "language_saved_warning": "语言已切换，但无法保存语言偏好：{message}",
        "config_validation_title": "配置校验失败",
        "config_validation": "配置不符合当前支持的格式，因此没有打开或保存；编辑器中现有的内容已保留。",
        "technical_detail": "技术细节：",
        "form_error_general": "一个或多个常用设置无效。",
        "form_error_size_format": "尺寸应写成“宽×高”，例如 512×512。",
        "form_error_size_range": "宽度和高度都必须在 1 到 8192 像素之间。",
        "form_error_sizes_empty": "请至少填写一个输出尺寸。",
        "form_error_sizes_duplicate": "请删除重复的输出尺寸。",
        "form_error_root_object": "JSON 配置的根节点必须是对象。",
        "form_error_output_empty": "请选择一个新的结果目录。",
        "form_error_cleanup": "请选择列表中提供的边缘清理方式。",
        "form_error_layout": "请选择列表中提供的布局方式。",
        "form_error_occupancy_format": "画布占比请输入 1 到 100 的数字。",
        "form_error_occupancy_range": "画布占比必须在 1% 到 100% 之间。",
        "form_error_preview_format": "预览帧数必须是整数。",
        "form_error_preview_range": "预览帧数必须在 1 到 10000 之间。",
    },
}


OPTION_KEYS: dict[str, dict[str, str]] = {
    "preset": {"pixel-character": "preset_pixel", "neutral": "preset_neutral"},
    "cleanup": {
        "off": "cleanup_off",
        "conservative": "cleanup_conservative",
        "strict": "cleanup_strict",
    },
    "layout": {"preserve": "layout_preserve", "shared_fit": "layout_shared_fit"},
}


def detect_language(language_name: str | None = None) -> str:
    candidate = language_name
    if candidate is None:
        try:
            candidate = locale.getlocale()[0]
        except (ValueError, TypeError):
            candidate = None
    normalized = (candidate or "").replace("_", "-").lower()
    return "zh-CN" if normalized.startswith("zh") else "en"


def text(language: str, key: str, **values: object) -> str:
    catalog = STRINGS.get(language, STRINGS["en"])
    value = catalog[key]
    return value.format(**values) if values else value


def option_labels(language: str, group: str) -> Mapping[str, str]:
    return {token: text(language, key) for token, key in OPTION_KEYS[group].items()}
